### ISSUE TITLE
Tag entry is black in Add dialog

### ISSUE THREAD

**Issue by ghost** [nickdvlpr/Redesign#2]
Hi there, fantastic job with the add-on!
I have some minor issues / improvement suggestions.

If I enable the add-on, the tag entry in the 'Add' dialog has a black background color.
Tested on two different Windows 10 installations, all other add-ons disabled, on one installation, nightmode add-on was never installed, so I guess it is not caused by it.

On a sidenote, maybe you could provide a link to the repo on the addon's description?

**Comment by nickdvlpr** [comment]
Thank you!

I noticed this too and haven't had time to play around with it to find the exact lines of code. I'll look into it some more later, but feel free to check yourself and submit a pull request if you find anything! It's likely in stylers.py or styles.py.

Good idea on adding a link there. I'll do so in the future when I know I'll have more time to support the add-on (I'd rather not be bombarded with requests when I can't work on them).

Thanks again!

**Comment by nickdvlpr** [comment]
Update: I figured it out. The next update will fix the Tag entry box's color issue.

**Comment by nickdvlpr** [comment]
**Completed** in Version 10.
