### ISSUE TITLE
Enhancement suggestion: Rounded borders for field inputs in editor

### ISSUE THREAD

**Issue by ghost** [nickdvlpr/Redesign#3]
Hi, 
just a simple enhancement suggestion: Maybe add a border-radius to the fields in the editor.
It would fit them better into the new theme, as right now, at least on Windows, they are very blocky and give a stark contrast with the rounded button theme of your add-on.

**Comment by nickdvlpr** [comment]
**Completed** in Version 10. Thank you for the suggestion!
