### ISSUE TITLE
sidebar enhancement

### ISSUE THREAD

**Issue by ecccap** [nickdvlpr/Redesign#5]
This is a suggestion for a replacement of the sidebar with enhanced features. I think it fits in neatly with the redesign.
From [reddit](https://www.reddit.com/r/Anki/comments/epxd53/addon_to_view_only_those_tags_from_a_specified/):

1. [an additional button in the browser + remove sidebar](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=browser.drawio#RzZZNb6MwEIZ%2FDVL3UAlMQpJjQ7pdbbXaQw6r3Utl8PCxcWxqhibZX78GzFeg6ocaqSecd8Ye%2B3knBsv198c7RbPkh2TALWKzo%2BVuLEIc27H1o1ROteLZTi3EKmUmqRO26T9oZhq1SBnkg0SUkmOaDcVQCgEhDjSqlDwM0yLJh1UzGsNI2IaUj9VfKcOkVpdk0enfII2TprLjrerInjbJ5iR5Qpk89CT31nJ9JSXWo%2F3RB17Ca7jU874%2BE203pkDgayYkD7vHTXjjs%2FlvZN%2F%2FPvy5j%2FNrs8oT5YU5sEU8rtdbs%2FSp3DSeDAnvsSh3uo6kwOu88ulGJ5BZpr1ed3E9istnUCBKUSfJDES5E4GgIhpCU0NvtipTzzCY2opEyUIwKLfv6PAhSRG2WTnd3Rx0t2ktwT034Sjl3JdcqmquG0URCUOt56jkDnoR5gXe3DMnMQ1HZm39PtCGDiiEY08ygO9A7gHVSaeYaOP1adjEh65znJnRkl7XzI1GTbPG7cKdn3pgLH2Dve6H2DvyVrPWTjZLBer9K725E%2BxXdMLH%2B%2BoshsaS%2BdhYMmGseyljZyNjc6AqTLQWUPXp%2BLn2Gb%2BJP4a9nAA4uxTAxfMAFeQFx1yPrkKqWP7Faq%2Fwjqi%2BzbNyWN1pgvItSlW9Sl6iG9BwF1d%2B%2FCyQpwIuR%2F3sNlpOQJ%2BvpqCvLkV9NaIuJEL9%2BsbyoJ%2Btcc8QtrheZviOztU%2Fu8%2BBKtb7qHJv%2FwM%3D)
2. [new interface](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=interface%20open.drawio#R7VtZc6M4EP41PE6K2%2FDoI57Z3UlVqvIwx0tKgAyaAGKEHNv761cCYQ5hx1nb2MnEL4bW3V93q9UtFGOarD8TkEV3OICxoqvBWjFmiq5rqqayP07ZlBRb1UpCSFAgKtWEB%2FQvrFoK6hIFMG9VpBjHFGVtoo%2FTFPq0RQOE4FW72gLH7VEzEEKJ8OCDWKZ%2BQwGNSqqjj2r6F4jCqBpZs92yJAFVZbGSPAIBXjVIxq1iTAnGtHxK1lMYc%2BZVfCnbzXeUbidGYEoPaRA9Pv2e%2BeNpYP2gwd%2B%2FHn%2F%2BE%2BafRC%2FPIF6KBSu6HbP%2BJgF65pOmG8EJ%2B%2FeSz3SywCn9lBc4jVkFTc8Y1pO6nD2F%2FN9bUorTspIf4xzyqaQUkgXwYTUIm20xTtlE8Gk7pE7wMg0gn7%2FGilcRovAh482N2YqJG6NFNIlF8QLF8RTHmBRtjYXjQ99n9JwS%2FAQbJZ5jmZYqliIkTtO34zc5WrEHEgrXDZLg8GeIE0jJhlURpRXYm%2FbrqhYdzRS0qCE2FQ0IaQ23HdeAsgeB6WvwVSWAA%2Bg%2F5RKr2fpom59tvqU4hR0mCxKIUchwnvmQo8sInFuIadBYFCQoCPgwvQDWEJ8JEbeNiKbJkFg9iOhnQ0RWOQrCPwgQwzVeRKRPR86HiC4hkvB97A%2FCxLZf1pJhMTF2bkyRcdS%2BVHWTZyDd3dFKLJJ3lWKSgLhoqh4%2BitrY48qxesf3Y5DnrfEDSAGKH%2F0IEOAzYXlcpshn8tgc5PrXf6srrqM4Nqs05kqS4mTzAkd2kznkp3ARJFdAVbXZZLotqTw8U3YnVFU3mGtXsqfpZhS%2F82ilZnS8iR53wh1UK82dWnkxcZ6rijtXXF0Z83pfIIgZa8SkPHISVZEE86Qy6OieYduHyGBgQScwzyNrjtUSNcOVRc0eVNQsWdQE1IbiFlCjnGIx0pFo7OE5UC3mMvfhZs%2B0uape1iIwsyTB5AwKk70LprGluNz6z9ly%2Feg4lCRbbKlwsdee78Kkjbc1kN22L43SaCBv6j17MxNlbD4AClKUJxf3ZDoaAS3NLGyRpBETXVUvbqXMC8u%2FaUrchkEIH8QrJjTCIU5BfFtTO4euus5XjDOBwi9I6UYwDywpbmPEGEg230X74uUHf7kZWdX7bN0snW1ee8DL8ZL4cJ%2Fii2AkBSSEdE9FXXCIs2UvxATGgKLndnS0D7Ci6ZgQsGlUyDBKad7o%2BZ4TGrEBu%2BOG6FYH%2FLLHWhS2U%2Fv%2F0mEZ1yQd1ygc2qmF47jdzJV2MwJXmDztManqASa1w9hQ7GW8qY8T5FcuYxXH105jLbfWsfIWrAtHKKuOz5AUiCH0I%2BW1wf%2B3BF7PEX3QwJkuh5dz1nXAzfA8ARsPvlFGd%2BL4WweimVrRBuX07mDIsWqyAoiiNCw8VPKu1KUT%2Bzd64syjIUE0NImRQ%2Bz9a0S%2F17s9e%2FvRKKk3fv5y%2Bn2%2Fyl2%2FvO87Z3EKJa%2Bvk3zQ1Q7a5URFoxrw1zqX3RyHq3bE5wy%2BpaFfk2854MnjYCHTTn7yOM6q94RKRNxRUyZMIdR7SHKOxh4L%2FPoDfACgs%2Bi9rWD7DvTk0NWZwsCd%2Bwtajy866MndcN6Kfb4GnXMO1TnjqnTOcP9UI3kwYPZVAVadaD4A2wmYdV2AXcbNfUuAja4KsGreDTfkC%2FY8BOVLSUddklxAu3FJcp9zITkmwcj1iszCCdwOp%2BN29BzuB80%2BG9Zl3Y5R0%2B%2FYuhov%2BB0Nvdq6K8MEkq03ahV12ddvpEXbyTvOroODOufJkx6Z8txzd2bCGKh%2BK0LoezOY%2FELNoanOkmFDZUDn7Oe6fXZqyn6N3OiwByizJ%2FU5qCUz%2B1L%2FHb7nEcj4Y7IO%2BUccN16WpDeC2GR5dWf1K%2FBgfI9zRBG%2F4T%2FzMKU4YRViXjAB%2FlNYQNmXbu7ee6XcNsrXYzNIEGMAf56xVaIsh%2Fc1aYKXNEYpQ7n66EOtibzFM%2Bvnr7TQkk3iYb4AhiqIYxjfLfnHIx2DLcU6dwZEWzLUF0rdLX%2FHSNcecdIHFSfZL2kFvUvNvsMki%2B4Kq%2FB%2BQtdmf%2FjwYqFrqy%2F%2F8KHZ59PsUwhRN77WI0SD6rMl39%2BjOMDvQ0WNnnt3xqDc7bOWHyr6plS0T4hOpKLstf78s8w41R%2FRGrf%2FAQ%3D%3D) (to show the idea. I left out the models b/c time)
   * opened on button click
   * The **crucial feature**: when deck(s) selected, hide tags and models that are not used within the deck(s). Vice versa for selecting tags and models.
   * selecting still operates the same search syntax as currently
   * what is not shown but should be included:
      * collapse button, where the (+) expand button has been activated
      * option to show unused decks/tags/models anyway
      * …?
   * The emojis and colors are not really necessary
   * Probably it's better to have decks, tags, and models not side-by-side but above each other (like in the current sidebar). This benefits deep hierarchies.

**Comment by nickdvlpr** [comment]
This is a little out of scope for this project, but if another group starts working on it I'd be happy to contribute!
